
###
## Get all inventory
GET http://localhost:5000/inventory
###

###
POST http://localhost:5000/inventory
content-type: application/json

{
    "name": "Lemonade760"
    , "description": "Freshly squeezed and absolutely delicious"
    , "ingredients": ["lemon","ice","water","sugar"]
    , "tags": ["drink","bubbly"]
    , "availability": true
    , "typeofPreparation": "In Stock"
    , "price": 3.50
}

###
delete http://localhost:5000/inventory/63e7378c5aad929118e32df4

###
get http://localhost:5000/inventory/63e72fc595b27d3d2f4e8732

###
## update contact:
PUT http://localhost:5000/inventory/63e7256f5088ca515d562127
content-type: application/json

{
    "name": "Lemonade760"
    , "description": "Freshly squeezed and absolutely delicious"
    , "ingredients": ["lemon","ice","water","sugar"]
    , "tags": ["drink","bubbly","wine"]
    , "availability": true
    , "typeofPreparation": "In Stock"
    , "price": 3.50
}


###
## Get all users
GET http://localhost:5000/users
###

###
POST http://localhost:5000/users
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "email"
    , "password": "password"
    , "userLevel": "1"
    , "address": "address"
}
###
###
delete http://localhost:5000/users/63e73955c6cf7b000a486950

###
get http://localhost:5000/users/63e73955c6cf7b000a486950

###
## update contact:
PUT http://localhost:5000/users/63e73955c6cf7b000a486950
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "email"
    , "password": "password123"
    , "userLevel": "1"
    , "address": "address"
}


//-----------------------------------------------------
//Production:
//-----------------------------------------------------

#https://cse-341-webbackend2-2.onrender.com/





###
## Get all inventory
GET https://cse-341-webbackend2-2.onrender.com/inventory
###

###
POST https://cse-341-webbackend2-2.onrender.com/inventory
content-type: application/json

{
    "name": "Lemonade760"
    , "description": "Freshly squeezed and absolutely delicious"
    , "ingredients": ["lemon","ice","water","sugar"]
    , "tags": ["drink","bubbly"]
    , "availability": true
    , "typeofPreparation": "In Stock"
    , "price": 3.50
}

###
delete https://cse-341-webbackend2-2.onrender.com/63e7378c5aad929118e32df4

###
get https://cse-341-webbackend2-2.onrender.com/63e72fc595b27d3d2f4e8732

###
## update contact:
PUT https://cse-341-webbackend2-2.onrender.com/63e7256f5088ca515d562127
content-type: application/json

{
    "name": "Lemonade760"
    , "description": "Freshly squeezed and absolutely delicious"
    , "ingredients": ["lemon","ice","water","sugar"]
    , "tags": ["drink","bubbly","wine"]
    , "availability": true
    , "typeofPreparation": "In Stock"
    , "price": 3.50
}


###
## Get all users
GET https://cse-341-webbackend2-2.onrender.com/users
###

###
POST https://cse-341-webbackend2-2.onrender.com/users
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "email"
    , "password": "password"
    , "userLevel": "1"
    , "address": "address"
}
###
###
delete https://cse-341-webbackend2-2.onrender.com/63e73955c6cf7b000a486950

###
get https://cse-341-webbackend2-2.onrender.com/63e73955c6cf7b000a486950

###
## update contact:
PUT https://cse-341-webbackend2-2.onrender.com/63e73955c6cf7b000a486950
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "email"
    , "password": "password123"
    , "userLevel": "1"
    , "address": "address"
}
